[package]
name = "rlb"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "1.6.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
